Algoritmo "Exercicio 2"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Jaqueline
// Descrição   : Tabuada
// Autor(a)    : Matheus Ferreira
// Data atual  : 20/09/2018
Var
   n,i,j,r:inteiro
Inicio
   Escreval("Entre com um número para fazer a tabuada: ")
   leia(n)
   limpatela
   i <- 1
   enquanto i <= 10 faca
      Escreval(n * i)
      i <- i + 1
   fimenquanto
Fimalgoritmo