Algoritmo "Exercício 1"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Faz a média de 2 números
// Autor(a)    : Matheus Ferreira
// Data atual  : 16/08/2018
Var
V1, V2: Inteiro
media: real
Inicio

Escreva("Digite o primeiro valor:")
leia(v1)
escreva("Digite o segundo valor:")
leia(v2)
media <- (V1+V2)/2
escreva("A media dos números é:", media)
Fimalgoritmo