Algoritmo "Exercício 6"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Média de um aluno
// Autor(a)    : Matheus Ferreira
// Data atual  : 16/08/2018
Var
nome:caracter
provaA, provaB:real
Inicio
Escreva("Entre com o seu nome:")
leia(nome)
escreva("Entre com a nota da prova A:")
leia(provaA)
escreva("Entre com a nota da prova B:")
leia(provaB)
Escreva("A sua média, ",nome,", é:",((provaA*2)+(provaB))/3)

Fimalgoritmo