Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Jaqueline
// Descrição   : Vetor X 3
// Autor(a)    : Matheus Ferreira
// Data atual  : 23/10/2018
Var
   num: vetor [1..10] de inteiro
   i: inteiro

Inicio
   Para i de 1 ate 10 faca
      Escreva("Entre com um número: ")
      leia(num[i])
   fimpara
   para i de 1 ate 10 faca
      Escreval(num[i]," X 3 = ", num[i] * 3)
   fimpara

Fimalgoritmo