Algoritmo "Exercício 2"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Par ou Impar
// Autor(a)    : Matheus Ferreira
// Data atual  : 30/08/2018
Var
   Num : inteiro


Inicio
   Escreva("Entre com um número")
   leia(Num)
   Se (Num%2 = 0 ) entao
      Escreva("O número é par")
   Senao
      Escreva("O número é impar")
   Fimse

Fimalgoritmo