Algoritmo "Exercício 3"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Positivo ou negativo
// Autor(a)    : Matheus Ferreira
// Data atual  : 30/08/2018
Var
   num : real


Inicio
   escreva("Entre com um número")
   leia(num)
   se num < 0 entao
      escreva("Número negativo")
   senao
      se (num >= 0) entao
         Escreva("Número Positivo")
      fimse
   fimse


Fimalgoritmo